version: "3"
services:
  app:
    image: app
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
volumes:
  mongo-data:
    driver: local
